import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
path='C:/Users/mayij/Desktop/DOC/DCP2021/TRAVEL DEMAND MODEL/'



bpm=['36005','36047','36061','36081','36085','36059','36103','36119','36087','36079','36071','36027',
     '09001','09009','34017','34003','34031','34013','34039','34027','34035','34023','34025','34029',
     '34037','34041','34019','34021']
geoxwalk=pd.read_csv(path+'POP/GEOIDCROSSWALK.csv',dtype=str)



# Clean up PUMS Household
pumshh=[]
for i in ['09','34','36']:
    pumshh+=[pd.read_csv(path+'PUMS/psam_h'+i+'.csv',dtype=str)]
pumshh=pd.concat(pumshh,axis=0,ignore_index=True)
pumshh['HHID']=pumshh['SERIALNO'].copy()
pumshh['PUMA']=pumshh['ST']+pumshh['PUMA']
pumshh=pd.merge(pumshh,geoxwalk[['PUMA2010','StateCounty']].drop_duplicates(keep='first'),how='left',left_on='PUMA',right_on='PUMA2010')
pumshh=pumshh[np.isin(pumshh['StateCounty'],bpm)].reset_index(drop=True)
pumshhgq=pumshh.loc[pumshh['TYPE']!='1',['HHID','PUMA']].reset_index(drop=True)
pumshhgq=pumshhgq.drop_duplicates(keep='first').reset_index(drop=True)
pumshhgq.to_csv(path+'PUMS/pumshhgq.csv',index=False)
pumshh=pumshh[pumshh['TYPE']=='1'].reset_index(drop=True)
pumshh['HHSIZE']=np.where(pumshh['NP']=='0','VAC',
                 np.where(pumshh['NP']=='1','SIZE1',
                 np.where(pumshh['NP']=='2','SIZE2',
                 np.where(pumshh['NP']=='3','SIZE3','SIZE4'))))
pumshh['HHTYPE']=np.where(pumshh['NP']=='0','VAC',
                 np.where(pumshh['HHT2']=='02','TYPE1',
                 np.where(pumshh['HHT2']=='04','TYPE1',
                 np.where(pumshh['HHT2']=='01','TYPE2',
                 np.where(pumshh['HHT2']=='03','TYPE2',
                 np.where(pumshh['HHT2']=='05','TYPE3',
                 np.where(pumshh['HHT2']=='09','TYPE3',
                 np.where(pumshh['HHT2']=='06','TYPE4',
                 np.where(pumshh['HHT2']=='10','TYPE4','TYPE5')))))))))
pumshh['HHINC']=pd.to_numeric(pumshh['HINCP'])
pumshh['HHINC']=np.where(pumshh['NP']=='0','VAC',
                np.where(pumshh['HHINC']<5000,'INC01',
                np.where(pumshh['HHINC']<10000,'INC02',
                np.where(pumshh['HHINC']<15000,'INC03',
                np.where(pumshh['HHINC']<20000,'INC04',
                np.where(pumshh['HHINC']<25000,'INC05',
                np.where(pumshh['HHINC']<35000,'INC06',
                np.where(pumshh['HHINC']<50000,'INC07',
                np.where(pumshh['HHINC']<75000,'INC08',
                np.where(pumshh['HHINC']<100000,'INC09',
                np.where(pumshh['HHINC']<150000,'INC10','INC11')))))))))))
pumshh['HHTEN']=np.where(pumshh['NP']=='0','VAC',
                np.where(pumshh['TEN']=='3','RENTER','OWNER'))
pumshh['HHSTR']=np.where(pumshh['NP']=='0','VAC',
                np.where(pumshh['BLD']=='02','STR1D',
                np.where(pumshh['BLD']=='03','STR1A',
                np.where(pumshh['BLD']=='04','STR2',
                np.where(pumshh['BLD']=='05','STR34',
                np.where(pumshh['BLD']=='06','STR59',
                np.where(pumshh['BLD']=='07','STR10',
                np.where(pumshh['BLD']=='08','STR10',
                np.where(pumshh['BLD']=='09','STR10','STRO')))))))))
pumshh['HHBLT']=np.where(pumshh['YBL']=='01','B39',
                np.where(pumshh['YBL']=='02','B40',
                np.where(pumshh['YBL']=='03','B50',
                np.where(pumshh['YBL']=='04','B60',
                np.where(pumshh['YBL']=='05','B70',
                np.where(pumshh['YBL']=='06','B80',
                np.where(pumshh['YBL']=='07','B90',
                np.where(pumshh['YBL']=='08','B00',
                np.where(pumshh['YBL']=='09','B00',
                np.where(pumshh['YBL']=='10','B00',
                np.where(pumshh['YBL']=='11','B00',
                np.where(pumshh['YBL']=='12','B00',
                np.where(pumshh['YBL']=='13','B00',
                np.where(pumshh['YBL']=='14','B10',
                np.where(pumshh['YBL']=='15','B10',
                np.where(pumshh['YBL']=='16','B10',
                np.where(pumshh['YBL']=='17','B10','B14')))))))))))))))))
pumshh['HHBED']=np.where(pumshh['BDSP']=='0','BED0',
                np.where(pumshh['BDSP']=='1','BED1',
                np.where(pumshh['BDSP']=='2','BED2',
                np.where(pumshh['BDSP']=='3','BED3',
                np.where(pumshh['BDSP']=='4','BED4','BED5')))))
pumshh['HHVEH']=np.where(pumshh['NP']=='0','VAC',
                np.where(pumshh['VEH']=='0','VEH0',
                np.where(pumshh['VEH']=='1','VEH1',
                np.where(pumshh['VEH']=='2','VEH2',
                np.where(pumshh['VEH']=='3','VEH3','VEH4')))))
pumshh=pumshh[['HHID','PUMA','WGTP','HHSIZE','HHTYPE','HHINC','HHTEN','HHSTR','HHBLT','HHBED','HHVEH']].reset_index(drop=True)
pumshh=pumshh.drop_duplicates(keep='first').reset_index(drop=True)
pumshh.to_csv(path+'PUMS/pumshh.csv',index=False)



# Clean up PUMS Person
pumspp=[]
for i in ['09','34','36']:
    pumspp+=[pd.read_csv(path+'PUMS/psam_p'+i+'.csv',dtype=str)]
pumspp=pd.concat(pumspp,axis=0,ignore_index=True)
pumspp['PPID']=pumspp['SERIALNO']+'|'+pumspp['SPORDER']
pumspp['HHID']=pumspp['SERIALNO'].copy()
pumspp['PUMA']=pumspp['ST']+pumspp['PUMA']
pumspp=pd.merge(pumspp,geoxwalk[['PUMA2010','StateCounty']].drop_duplicates(keep='first'),how='left',left_on='PUMA',right_on='PUMA2010')
pumspp=pumspp[np.isin(pumspp['StateCounty'],bpm)].reset_index(drop=True)
pumspp['POWPUMA']=np.where(pd.isna(pumspp['POWPUMA']),'',pumspp['POWSP']+pumspp['POWPUMA'])
pumspp['POWPUMA']=[str(x)[1:] for x in pumspp['POWPUMA']]
pumspp['POWPUMA']=np.where(pumspp['POWPUMA']=='','NW',pumspp['POWPUMA'])
pumspp['PPSEX']=np.where(pumspp['SEX']=='1','MALE','FEMALE')
pumspp['AGEP']=pd.to_numeric(pumspp['AGEP'])
pumspp['PPAGE']=np.where(pumspp['AGEP']<=5,'AGE01',
                np.where(pumspp['AGEP']<=9,'AGE02',
                np.where(pumspp['AGEP']<=14,'AGE03',
                np.where(pumspp['AGEP']<=19,'AGE04',
                np.where(pumspp['AGEP']<=24,'AGE05',
                np.where(pumspp['AGEP']<=29,'AGE06',
                np.where(pumspp['AGEP']<=34,'AGE07',
                np.where(pumspp['AGEP']<=39,'AGE08',
                np.where(pumspp['AGEP']<=44,'AGE09',
                np.where(pumspp['AGEP']<=49,'AGE10',
                np.where(pumspp['AGEP']<=54,'AGE11',
                np.where(pumspp['AGEP']<=59,'AGE12',
                np.where(pumspp['AGEP']<=64,'AGE13',
                np.where(pumspp['AGEP']<=69,'AGE14',
                np.where(pumspp['AGEP']<=74,'AGE15',
                np.where(pumspp['AGEP']<=79,'AGE16',
                np.where(pumspp['AGEP']<=84,'AGE17','AGE18')))))))))))))))))
pumspp['PPRACE']=np.where(pumspp['HISP']!='01','HSP',
                 np.where(pumspp['RAC1P']=='1','WHT',
                 np.where(pumspp['RAC1P']=='2','BLK',
                 np.where(pumspp['RAC1P']=='3','NTV',
                 np.where(pumspp['RAC1P']=='4','NTV',
                 np.where(pumspp['RAC1P']=='5','NTV',
                 np.where(pumspp['RAC1P']=='6','ASN',
                 np.where(pumspp['RAC1P']=='7','PCF',
                 np.where(pumspp['RAC1P']=='8','OTH',
                 np.where(pumspp['RAC1P']=='9','TWO','OT'))))))))))
pumspp['PPEDU']=np.where(pumspp['AGEP']<18,'U18',
                np.where((pumspp['AGEP']<=24)&(np.isin(pumspp['SCHL'],['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15'])),'U24LH',
                np.where((pumspp['AGEP']<=24)&(np.isin(pumspp['SCHL'],['16','17'])),'U24HS',
                np.where((pumspp['AGEP']<=24)&(np.isin(pumspp['SCHL'],['18','19','20'])),'U24AD',
                np.where((pumspp['AGEP']<=24)&(np.isin(pumspp['SCHL'],['21','22','23','24'])),'U24BD',
                np.where((pumspp['AGEP']>=25)&(np.isin(pumspp['SCHL'],['01','02','03','04','05','06','07','08','09','10','11'])),'O25G9',
                np.where((pumspp['AGEP']>=25)&(np.isin(pumspp['SCHL'],['12','13','14','15'])),'O25LH',
                np.where((pumspp['AGEP']>=25)&(np.isin(pumspp['SCHL'],['16','17'])),'O25HS',
                np.where((pumspp['AGEP']>=25)&(np.isin(pumspp['SCHL'],['18','19'])),'O25SC',
                np.where((pumspp['AGEP']>=25)&(np.isin(pumspp['SCHL'],['20'])),'O25AD',
                np.where((pumspp['AGEP']>=25)&(np.isin(pumspp['SCHL'],['21'])),'O25BD',
                np.where((pumspp['AGEP']>=25)&(np.isin(pumspp['SCHL'],['22','23','24'])),'O25GD','OT'))))))))))))
pumspp['PPSCH']=np.where(pumspp['SCHG']=='01','PR',
                np.where(pumspp['SCHG']=='02','KG',
                np.where(pumspp['SCHG']=='03','G14',
                np.where(pumspp['SCHG']=='04','G14',
                np.where(pumspp['SCHG']=='05','G14',
                np.where(pumspp['SCHG']=='06','G14',
                np.where(pumspp['SCHG']=='07','G58',
                np.where(pumspp['SCHG']=='08','G58',
                np.where(pumspp['SCHG']=='09','G58',
                np.where(pumspp['SCHG']=='10','G58',
                np.where(pumspp['SCHG']=='11','HS',
                np.where(pumspp['SCHG']=='12','HS',
                np.where(pumspp['SCHG']=='13','HS',
                np.where(pumspp['SCHG']=='14','HS',
                np.where(pumspp['SCHG']=='15','CL',
                np.where(pumspp['SCHG']=='16','GS','NS'))))))))))))))))
pumspp['NAICS']=[str(x)[:2] for x in pumspp['NAICSP']]
pumspp['PPIND']=np.where(pumspp['AGEP']<16,'U16',
                np.where(pumspp['ESR']=='6','NLF',
                np.where(pumspp['ESR']=='6','NLF',
                np.where(pumspp['ESR']=='4','MIL',
                np.where(pumspp['ESR']=='5','MIL',
                np.where(pumspp['ESR']=='3','CUP',
                np.where(pumspp['NAICS']=='11','AGR',
                np.where(pumspp['NAICS']=='21','EXT',
                np.where(pumspp['NAICS']=='23','CON',
                np.where(pumspp['NAICS']=='31','MFG',
                np.where(pumspp['NAICS']=='32','MFG',
                np.where(pumspp['NAICS']=='33','MFG',
                np.where(pumspp['NAICS']=='3M','MFG',
                np.where(pumspp['NAICS']=='42','WHL',
                np.where(pumspp['NAICS']=='44','RET',
                np.where(pumspp['NAICS']=='45','RET',
                np.where(pumspp['NAICS']=='4M','RET',
                np.where(pumspp['NAICS']=='48','TRN',
                np.where(pumspp['NAICS']=='49','TRN',
                np.where(pumspp['NAICS']=='22','UTL',
                np.where(pumspp['NAICS']=='51','INF',
                np.where(pumspp['NAICS']=='52','FIN',
                np.where(pumspp['NAICS']=='53','RER',
                np.where(pumspp['NAICS']=='54','PRF',
                np.where(pumspp['NAICS']=='55','MNG',
                np.where(pumspp['NAICS']=='56','WMS',
                np.where(pumspp['NAICS']=='61','EDU',
                np.where(pumspp['NAICS']=='62','MED',
                np.where(pumspp['NAICS']=='71','ENT',
                np.where(pumspp['NAICS']=='72','ACC',
                np.where(pumspp['NAICS']=='81','SRV',
                np.where(pumspp['NAICS']=='92','ADM','OTH'))))))))))))))))))))))))))))))))
pumspp['PPMODE']=np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='1'),'DA',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='2'),'CP2',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='3'),'CP3',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='4'),'CP4',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='5'),'CP56',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='6'),'CP56',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='7'),'CP7',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='8'),'CP7',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='9'),'CP7',
                 np.where((pumspp['JWTRNS']=='01')&(pumspp['JWRIP']=='10'),'CP7',
                 np.where(pumspp['JWTRNS']=='02','BS',
                 np.where(pumspp['JWTRNS']=='03','SW',
                 np.where(pumspp['JWTRNS']=='04','CR',
                 np.where(pumspp['JWTRNS']=='05','LR',
                 np.where(pumspp['JWTRNS']=='06','FB',
                 np.where(pumspp['JWTRNS']=='07','TC',
                 np.where(pumspp['JWTRNS']=='08','MC',
                 np.where(pumspp['JWTRNS']=='09','BC',
                 np.where(pumspp['JWTRNS']=='10','WK',
                 np.where(pumspp['JWTRNS']=='11','HM',
                 np.where(pumspp['JWTRNS']=='12','OT','NW')))))))))))))))))))))
pumspp['JWMNP']=pd.to_numeric(pumspp['JWMNP'])
pumspp['PPTIME']=np.where(pd.isna(pumspp['JWMNP']),'NWHM',
                 np.where(pumspp['JWMNP']<5,'TM01',
                 np.where(pumspp['JWMNP']<10,'TM02',
                 np.where(pumspp['JWMNP']<15,'TM03',
                 np.where(pumspp['JWMNP']<20,'TM04',
                 np.where(pumspp['JWMNP']<25,'TM05',
                 np.where(pumspp['JWMNP']<30,'TM06',
                 np.where(pumspp['JWMNP']<35,'TM07',
                 np.where(pumspp['JWMNP']<40,'TM08',
                 np.where(pumspp['JWMNP']<45,'TM09',
                 np.where(pumspp['JWMNP']<60,'TM10',
                 np.where(pumspp['JWMNP']<90,'TM11','TM12'))))))))))))
pumspp['JWDP']=pd.to_numeric(pumspp['JWDP'])
pumspp['PPDEPART']=np.where(pd.isna(pumspp['JWDP']),'NWHM',
                   np.where(pumspp['JWDP']<=18,'DP01',
                   np.where(pumspp['JWDP']<=24,'DP02',
                   np.where(pumspp['JWDP']<=30,'DP03',
                   np.where(pumspp['JWDP']<=36,'DP04',
                   np.where(pumspp['JWDP']<=42,'DP05',
                   np.where(pumspp['JWDP']<=48,'DP06',
                   np.where(pumspp['JWDP']<=54,'DP07',
                   np.where(pumspp['JWDP']<=60,'DP08',
                   np.where(pumspp['JWDP']<=66,'DP09',
                   np.where(pumspp['JWDP']<=78,'DP10',
                   np.where(pumspp['JWDP']<=84,'DP11',
                   np.where(pumspp['JWDP']<=90,'DP12',
                   np.where(pumspp['JWDP']<=114,'DP13',
                   np.where(pumspp['JWDP']<=150,'DP14','OTH')))))))))))))))
pumsppgq=pumspp[np.isin(pumspp['RELSHIPP'],['37','38'])].reset_index(drop=True)
pumsppgq=pumsppgq[['PPID','HHID','PUMA','POWPUMA','PWGTP','PPSEX','PPAGE','PPRACE','PPEDU','PPSCH',
                   'PPIND','PPMODE','PPTIME','PPDEPART']].reset_index(drop=True)
pumsppgq=pumsppgq.drop_duplicates(keep='first').reset_index(drop=True)
pumsppgq.to_csv(path+'PUMS/pumsppgq.csv',index=False)
pumspp=pumspp[~np.isin(pumspp['RELSHIPP'],['37','38'])].reset_index(drop=True)
pumspp=pumspp[['PPID','HHID','PUMA','POWPUMA','PWGTP','PPSEX','PPAGE','PPRACE','PPEDU','PPSCH',
               'PPIND','PPMODE','PPTIME','PPDEPART']].reset_index(drop=True)
pumspp=pumspp.drop_duplicates(keep='first').reset_index(drop=True)
pumspp.to_csv(path+'PUMS/pumspp.csv',index=False)

